# -*- coding: utf-8 -*-
"""도심속바다축제 tf-idf 200327.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JW98SacA6tHOXT3HlPJUVVsA_y-Hkf5c
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install konlpy

import codecs
from bs4 import BeautifulSoup
from konlpy.tag import Kkma
from gensim.models.word2vec import Word2Vec

import pandas as pd
data = pd.read_csv('/content/drive/My Drive/Toy Project/healing_dosim_twitter.csv', sep=',', encoding='utf-8')
data.head()

kkma = Kkma()

sentence_list = []
for sent in data[0:1000][' text']:
  
  news_nouns = kkma.nouns(sent)
  word_list = []
  for word in news_nouns:
      word_list.append(word)
  sentence_list.append(word_list)

print(sentence_list[0:10])

model = Word2Vec(sentence_list, size=100)
model.most_similar('동작')

print(model.most_similar(positive=['힐링'],negative=['도심'],topn=5))

print(model.similarity('힐링','사람'))







